### ISSUE TITLE
Alerta docker image

### ISSUE THREAD

**Issue by kavyakul** [alerta/prometheus-config#1]
Hi,
I am using alerta/alert-web latest docker image, please let me know if I can integrate Prometheus with alerta using this image.
when I check <alerta host>:<alerta port>/api/ I cant find Prometheus webhook, probably because its a new development.

**Comment by satterly** [comment]
Thanks for the reminder. I've just updated the docker container with the latest Alerta version 4.7.5. Let me know if you have any problems with the updated container.
