### ISSUE TITLE
Prometheus alert notification to OMNIBUS 

### ISSUE THREAD

**Issue by venkatraj-icp** [alerta/prometheus-config#10]
Hi All,

Iam new to this Prometheus 
I have configured OMNIBUS with message probe in stand alone RHEL VM
My Prometheus running as a Docker Container 
I want to configure Prometheus alerts forward to IBM OMNIBUS 
Please let me know the possibilities and share me if any document  

Regards,
Venkatraj

**Comment by satterly** [comment]
Sorry, this repo relates only to how Alerta integrates with Prometheus. For other tools, such as IBM OMNIBUS, I suggest you forward your issue directly to @prometheus.
