### ISSUE TITLE
Alertmanager Cluster

### ISSUE THREAD

**Issue by MaartenMol** [alerta/prometheus-config#17]
Hi, I really like Alerta so far. It does what Alertmanager and Unsee are missing. However, I can' t seem to find the best way to configure Alerta with a Alertmanager cluster.

Is there a best practice for this or is it not recommended?

**Comment by satterly** [comment]
I assume you define the webhook configuration the same across your Alertmanager cluster and it takes care of only sending the webhook once. Is that not the case?

If you're just after config help then try the `prometheus-config` [README](https://github.com/alerta/prometheus-config) and check out the `plugin` @n0guest  mentioned that provides [bi-directional integration](https://github.com/alerta/alerta-contrib/tree/master/plugins/prometheus).

**Comment by MaartenMol96** [comment]
@n0guest @satterly its about bi-directional integration, you give the following config for alerta:

`ALERTMANAGER_API_URL = 'http://alertmanager1:9093'`

How would i confifure the second alertmanager? I am using Alerta in a Docker-Compose

(Thx for the fast repsonse btw)

**Comment by n0guest** [comment]
> How would i configure the second alertmanager? I am using Alerta in a Docker-Compose

1) alertmanagers should be in mesh to share "silences" between themselves
2) all alertmanagers in configs should have a route to alerts webhook

In that case, i assume, it didn't matter which alertmanager will receive a "callback" from Alerta (i.e. incoming request for creating a silence for an event, which acknowledged in Alerta). One of alertmanagers will accept added "silence" and share it with his mesh peers.

**Comment by MaartenMol96** [comment]
1. my alertmanagers are in mesh
2. all alertmanagers have the same config with the webhook for Alerta

So I shouldn't config a ALERTMANAGER_API_URL and let it be picked by the externalURL attribute?

**Comment by satterly** [comment]
> So I shouldn't config a ALERTMANAGER_API_URL and let it be picked by the externalURL attribute?

Yes, that's the idea. If it doesn't work let us know.

**Comment by MaartenMol96** [comment]
@satterly I have tried but I am getting the following URLs: http://5c7c674527d9:9093, I think this has something to do with docker?

**Comment by satterly** [comment]
There's an incantation of docker that works but it's not obvious what it is. See https://github.com/docker/compose/issues/2925 for more info.

Maybe someone else on here with more knowledge of real-world docker deploys can chip in. 🙏
