### ISSUE TITLE
How to altera list type field convert to a Prometheus rule configuration

### ISSUE THREAD

**Issue by net592** [alerta/prometheus-config#23]
How to altera convert to a Prometheus rule configuration
example :
alerta data:
"correlate": ["cpu","load"],

Prometheus rules:
labels:
         correlate: ['cpu','load']
or
labels:
         correlate:
         -   cpu
         -   load

All failure
./promtool check rules Prometheus.rules    
Checking Prometheus.rules
  FAILED:
yaml: unmarshal errors:
  line : cannot unmarshal !!seq into string

**Comment by satterly** [comment]
Use ...
```
labels:
  correlate: cpu,load
```
