### ISSUE TITLE
Permission or scope for user

### ISSUE THREAD

**Issue by prasenforu** [alerta/prometheus-config#26]
As per my observation default ```user```  permission is read & write.

![image](https://user-images.githubusercontent.com/19322497/71566216-ca645980-2adb-11ea-9bc0-b5aa0b2a0e67.png)

As ```user```  having write permission so ```user``` can delete any alert. which I do not want. I want  separate permission or scope so apart from ```delete``` user can do rest.

Not sure if that is available or not, if available can anyone please guide me.

**Comment by satterly** [comment]
You can change the default user permissions using `USER_DEFAULT_SCOPES`. See https://docs.alerta.io/en/latest/configuration.html#authentication-settings
