### ISSUE TITLE
can we have multiple urls in alertmanager config 

### ISSUE THREAD

**Issue by sri-pavan** [alerta/prometheus-config#28]
Currently we have one url in our alertmanager config 

can we add two urls ? like below 

 - name: aaaaaa
   email_configs:
   - to: 'aaa@aaa.com'
     send_resolved: true
   webhook_configs:
    - url: http://aaaaaa/prometheus/alerting,http://bbbbbbbb/prometheus/alerting

**Comment by bernhardkaindl** [comment]
The answer is easy: Simply add the second receiver to your alertmanager config,
and add it to the `route:` section. Be sure to add `continue: true` to the default receiver,
(and some match seems to be needed in it too), to ensure that alertmanager continues to the second receiver after successfully matching on the default receiver (that is, when you want alerts to be sent to both receivers urls).

See: https://prometheus.io/docs/alerting/latest/configuration/#route

This answers the (old, likely obsolete) question. ;-)
