### ISSUE TITLE
Prometheus webhook_configs returns 404

### ISSUE THREAD

**Issue by gfliker** [alerta/prometheus-config#3]
While hitting this end point from the Alert manager were getting a 404
/webhooks/prometheus

Please advise and many thanks

**Comment by satterly** [comment]
This is a `POST` only endpoint.

Try `curl -XPOST /webhooks/prometheus` and you should get something like ...
```
{
  "status": "error",
  "message": "no alerts in Prometheus notification payload"
}
```

**Comment by satterly** [comment]
Or if you running alerta in a docker container you'll need to add `/api` to the endpoint path like this ...
`/api/webhooks/prometheus`.

**Comment by gfliker** [comment]
Im using the docker version ,will verify soon

Thx

**Comment by satterly** [comment]
You might find this answer useful ... https://github.com/alerta/prometheus-config/issues/2#issuecomment-188719201

**Comment by satterly** [comment]
@gfliker I've added a specific reference in the [README](https://github.com/alerta/prometheus-config#configuration---alertmanager) to configuring Alertmanager when deploying Alerta using a Docker container so I'll close this issue as resolved. Open a new issue if you're still having problems.
